# Generated by Django 4.2.4 on 2023-09-09 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('product_description', models.TextField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
                ('product_images1', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images2', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images3', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('category', models.CharField(max_length=255, null=True)),
                ('brand_name', models.CharField(max_length=255, null=True)),
                ('sizeQuantity', models.CharField(max_length=255, null=True)),
                ('petCompatibility', models.CharField(max_length=255, null=True)),
                ('agesizesuitability', models.CharField(max_length=255, null=True)),
                ('colorsVariations', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
