# Generated by Django 4.2.4 on 2023-09-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
