# Generated by Django 4.2.4 on 2023-09-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
