# Generated by Django 4.2.4 on 2023-09-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0013_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pet',
            field=models.CharField(max_length=10),
        ),
    ]
