# Generated by Django 4.2.4 on 2023-09-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0015_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
