# Generated by Django 4.2.4 on 2023-09-20 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0019_remove_productsubcategory_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSubcategory',
            new_name='CatSubcategory',
        ),
        migrations.CreateModel(
            name='DogSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(default=None, max_length=100, null=True)),
                ('pet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.petcategory')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indexapp.productcategory')),
            ],
        ),
    ]
