# Generated by Django 4.2.4 on 2023-09-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0022_productsubcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
