# Generated by Django 4.2.4 on 2023-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0025_alter_petcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceUnit',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
