# Generated by Django 4.2.4 on 2023-09-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0026_product_priceunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='priceUnit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
