# Generated by Django 4.2.4 on 2023-09-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0034_product_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='m',
            field=models.CharField(blank=True, default='1', max_length=255, null=True),
        ),
    ]
