# Generated by Django 4.2.4 on 2023-09-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0036_alter_product_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
