# Generated by Django 4.2.4 on 2023-09-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0037_alter_product_quantity_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
