# Generated by Django 4.2.4 on 2023-09-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0038_alter_product_quantity_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_value',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
